sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'git push origin dhruvaldarji@http://dhruvaldarji.com/public_html/ruchidarji.com/Development/Development.git'
